# Generated by Django 6.0.1 on 2026-01-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_observaciones_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='factura_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
