# Generated by Django 6.0.1 on 2026-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_material_codigo_barras_movimiento_factura_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
