# Generated by Django 6.0.1 on 2026-01-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_marca_movimiento_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='inventario.marca'),
        ),
        migrations.AddField(
            model_name='material',
            name='ultimo_precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
