# Generated by Django 5.2.10 on 2026-01-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_material_marca_material_ultimo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
