# Generated by Django 5.2.10 on 2026-01-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_movimiento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Traslado', 'Traslado'), ('Edicion', 'Edición'), ('Ajuste', 'Ajuste'), ('Devolucion', 'Devolución')], max_length=20),
        ),
    ]
