# Generated by Django 5.2.10 on 2026-01-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_movimiento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abreviacion', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
