# Generated by Django 5.2.10 on 2026-02-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subbodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbodegas', to='inventario.bodega')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='subbodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.subbodega'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='subbodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to='inventario.subbodega'),
        ),
    ]
