# Generated by Django 5.2.10 on 2026-02-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_subbodega_movimiento_subbodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbodega',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventario.subbodega'),
        ),
    ]
