# Generated by Django 5.2.10 on 2026-02-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_subbodega_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='ultimo_precio',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='precio',
        ),
    ]
