# Generated by Django 5.2.10 on 2026-02-17 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_material_ultimo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
